### ISSUE TITLE
Add N+1 Score Indication in UI

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-ui#319] opened 2023-12-12 02:23 UTC
Like the "Impact" value, add the "Criticality" information.
Use the same value to string key and gradient from performance impact to color the value

<img width="1216" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3hPQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ad538640c8e03fdd7706a124a4f6f2e9d47307a2/image.png" alt="image.png" />

Also add the same information from the span side

**Comment by kshmidt-digma** [comment] 2023-12-18 10:27
Closed as a duplicate of https://github.com/digma-ai/digma-ui/issues/316

**Closed by kshmidt-digma** 2023-12-18 10:27 UTC
