### ISSUE TITLE
analytics tab view -  mixed insights, issues displayed

### ISSUE THREAD

**Issue by shaykeren** [digma-ai/digma-ui#955] opened 2024-08-04 10:08 UTC
STR
1. observe analytics tab
2. go to issues
3. go back to analytics
4. wait ~10 sec and observe that the data is being changed to issues and then back to analytics

**Comment by kshmidt-digma** [comment] 2024-08-04 10:11
Duplicate of #946
Closed in #952

**Closed by kshmidt-digma** 2024-08-04 10:11 UTC
Labels: bug
