### ISSUE TITLE
code button doesn't always work

### ISSUE THREAD

**Issue by shalom938** [digma-ai/digma-ui#392] opened 2024-01-29 10:44 UTC
[Screencast from 2024-01-29 12-37-48.webm](https://github.com/digma-ai/digma-ui/assets/170266/ed46d01b-b5c1-4e73-98be-4ff119fe4e7f)

**Comment by kshmidt-digma** [comment] 2024-02-02 20:12
Closed as duplicate of https://github.com/digma-ai/jaeger-ui/issues/43

**Closed by kshmidt-digma** 2024-02-02 20:12 UTC
Labels: bug
